server:
  port: 9001
  servlet:
    context-path: /api

app:
  webhook:
    executor:
      core-pool-size: 10
      max-pool-size: 20
  job:
    webhook-host: http://localhost:9001
    executor:
      core-pool-size: 10
      max-pool-size: 20